language: java
jdk:
- oraclejdk8
deploy:
  provider: heroku
  api_key:
    secure: g+WnMEjS56vvuZQeH3o7C3KEhsbbutMRFIWE/lz/VzTB9gMzBroc2LQicZ3CO4jZL04pVkAVIKwln9MH+8N/Sxmv3kHN1Vmq014ti17lCzekpXtIMUHCeI5Z4u2FUrfsVeU5Wwlo3KnVzwZqxZl2LAAiuB7JX7eaflgkt7NVeEqz1crSdiw/Qo83CoaFjNPjP9QL+pL/IGONAemf0i2ycaUVtrbvzAiwWdw9Jcyd2yFbd2p71o03QfzEdJKf8O3HIdEBC7CZZ8ad3CHU1ugDmgBGRr6SgGbA1qzjRKJPSzLV6rm/59MGAdOtLhs0CnAB5PZjpqNB4Iy1a44x6swYga9mhoo4lmeUdzF7bW0oQqVIUbTToyCz7+vC3cRiktzjQMEp15cReZ5qXKTNctikycXPUHmMDj3F5XzWbarB0hMaRbPJt/+1LMcjAN1TAohenH4dMD0pRuZhWtpS5EuED99sVVKOiT9Sa8qYHr5xcDUgxGGgdB/aDtSRcamldx5YJwTMeo7XfP8tJv2RWMtEJZOGzQTxMIQiSmPVcdwUNGeL3xWy7gwHp89Dm9ahY2gl8JDzOJqt3BlUFL4gqZr2hXZuInJyHTSu4aUiugW+h9AThHhMmVuQ+vBF4kwICLGXoV4bvT6K56JpkRBEV1600sOBYGctJIkyMX59dGhqtJw=
